// this is a temp solution
//
#define ADD "/"
#define END_DIRECTORY "/"
#define END_FILE

#define NAME_ENGINE_DIRECTORY "engine"
#define NAME_LOG_FILE "build_output.log"
#define NAME_BUILD_STATUS_DIRECTORY "build_status"
#define NAME_STATUS_FILE "build_status.json"
#define NAME_BUILD_WRAPPER_BASH_SCRIPT "build_wrapper.sh"
#define NAME_RUN_BASH_SCRIPT "run.sh"


#define PATH_TO_ROOT ".."
#define PATH_ASSET_BROWSER_ROOT PATH_TO_ROOT 
#define PATH_ENGINE PATH_TO_ROOT ADD NAME_ENGINE_DIRECTORY
#define PATH_BUILD_STATUS_DIRECTORY PATH_ENGINE ADD NAME_BUILD_STATUS_DIRECTORY 

#define PATH_STATUS_FILE  PATH_BUILD_STATUS_DIRECTORY ADD NAME_STATUS_FILE END_FILE
#define PATH_LOG_FILE  PATH_BUILD_STATUS_DIRECTORY ADD NAME_LOG_FILE END_FILE
#define SH_BUILD_WRAPPER_BASH_SCRIPT PATH_ENGINE ADD NAME_BUILD_WRAPPER_BASH_SCRIPT
#define SH_RUN_SCRIPT PATH_ENGINE ADD NAME_RUN_BASH_SCRIPT


#define DIRECTORY_ASSET_BROWSER_ROOT PATH_ASSET_BROWSER_ROOT END_DIRECTORY
#define DIRECTORY_ENGINE PATH_ENGINE END_DIRECTORY
#define DIRECTORY_BUILD_STATUS PATH_ENGINE ADD NAME_BUILD_STATUS_DIRECTORY END_DIRECTORY
